[workspace]
resolver = "3"
members = [
    "crates/veriflat_kernel_core",
    "crates/veriflat_alloc_page",
    "crates/veriflat_syscall_alloc_quota",
    "crates/veriflat_syscall_new_thread",
]
exclude = ["verus"]

[package]
name = "VeriFlat"
version = "0.1.0"
edition = "2024"

[lib]
name = "veriflat_monolith"
path = "src/lib.rs"

[dependencies]
vstd = { path = "verus/source/vstd" }

[features]
split-crates = []
