[package]
name = "veriflat_map_4k"
version = "0.1.0"
edition = "2024"

[lib]
path = "../../src/kernel/implementation/veriflat_map_4k.rs"

[dependencies]
vstd = { path = "../../verus/source/vstd" }
veriflat_kernel_core = { path = "../veriflat_kernel_core" }
veriflat_alloc_page = { path = "../veriflat_alloc_page" }

[package.metadata.verus]
verify = true
