[package]
name = "veriflat_alloc_page"
version = "0.1.0"
edition = "2024"

[lib]
path = "../../src/kernel/implementation/veriflat_alloc_page.rs"

[dependencies]
vstd = { path = "../../verus/source/vstd" }
veriflat_kernel_core = { path = "../veriflat_kernel_core" }

[package.metadata.verus]
verify = true
