pub mod syscall_new_process_spec;
mod syscall_new_process_with_iommu_publish;
mod syscall_new_process_publish;
pub mod syscall_new_process_helpers;
mod syscall_new_process_with_iommu_helpers;
pub mod syscall_new_process;
pub mod syscall_new_process_with_endpoint;
pub mod syscall_new_process_with_iommu_and_endpoint;
