#[cfg(not(feature = "split-crates"))]
pub mod syscall_alloc_quota;
#[cfg(not(feature = "split-crates"))]
pub mod syscall_new_thread;
#[cfg(not(feature = "split-crates"))]
pub mod syscall_new_thread_with_endpoint;
pub mod locker_unlocker;
#[cfg(not(feature = "split-crates"))]
pub mod allocate_free_4k_page;
